site_name: rattopedia
site_url: https://rattopos.github.com/rattopedia
theme:
  name: material
  logo: assets/logo.png
plugins:
  - blog
markdown_extensions:
  - pymdownx.arithmatex:
     generic: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.details
